### ISSUE TITLE
Support OS-independent environment.yml

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas-actions.build#1]
Currently this action supports OS-specific environment files (eg. `env_win.yml`, `env_osx.yml`), but I think it would be meaningful to also support `environment.yml` for those cases in which one env yml file is enough for all platforms.

**Comment by Licini** [comment]
@gonzalocasas Just updated to https://github.com/compas-dev/compas-actions.build/releases/tag/v1.2.0 which supports this.

**Comment by gonzalocasas** [comment]
Thanks!
